export const SENDMESSAGES_REQUEST = "SENDMESSAGES_REQUEST";
export const SENDMESSAGES_SUCCESS = "SENDMESSAGES_SUCCESS";
export const SENDMESSAGES_FAIL = "SENDMESSAGES_FAIL";


export const SENDMESSAGESWITHFILE_REQUEST = "SENDMESSAGESWITHFILE_REQUEST";
export const SENDMESSAGESWITHFILE_SUCCESS = "SENDMESSAGESWITHFILE_SUCCESS";
export const SENDMESSAGESWITHFILE_FAIL = "SENDMESSAGESWITHFILE_FAIL";


export const GETMESSAGES_REQUEST = "GETMESSAGES_REQUEST";
export const GETMESSAGES_SUCCESS = "GETMESSAGES_SUCCESS";
export const GETMESSAGES_FAIL = "GETMESSAGES_FAIL";


